server:
  port: 5337
  tomcat:
    max-http-post-size: 2048MB
#thymeleaf配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
  #静态资源配置
  resources:
    static-locations: classpath:/
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 2048MB
      max-request-size: 2048MB
#fileDirectory: D:\work\develop\vamtoo-git\file-demo\src\main\resources\file\
fileDirectory: /home/zbl/file/